name: Generate static site

env:
  branch: gh-pages
  dir: static

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      
      - name: run gonews
        run: |
          go run main.go generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
      